# Base image, assuming you're using Python 3.9
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container

COPY ./weights/ /app/.cxas/weights

ENV CXAS_PATH=/app/

# Install system-level dependencies (including libGL and libglib)
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libgl1-mesa-glx \
    libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
# If you're using conda and the environment file is cxas_requirements.yml
RUN pip install --upgrade pip && \
    pip install setuptools wheel && \
    pip install torch torchvision torchaudio && \
    pip install cxas==0.0.15

# # Optional: if you want to provide a default entry point for your CLI tool
ENTRYPOINT ["cxas"]
